// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB41Y0IBCAhWtOtJejcnr4bNAyIvs7hy1g',
    appId: '1:661569067297:web:3a42dde95e91e0138cc660',
    messagingSenderId: '661569067297',
    projectId: 'eaglone-auth',
    authDomain: 'eaglone-auth.firebaseapp.com',
    storageBucket: 'eaglone-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwwE_q2mqqQRr8_oENqzQBP3z0GWIqTT8',
    appId: '1:661569067297:android:5d03050edc15d1ca8cc660',
    messagingSenderId: '661569067297',
    projectId: 'eaglone-auth',
    storageBucket: 'eaglone-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Frskj1kaNAHxpSv9bx1Dq8AvNlPnVbw',
    appId: '1:661569067297:ios:9da3a479287059338cc660',
    messagingSenderId: '661569067297',
    projectId: 'eaglone-auth',
    storageBucket: 'eaglone-auth.appspot.com',
    iosClientId: '661569067297-iromejaju6dcu28rop5e8e5of2n9kmlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eaglone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Frskj1kaNAHxpSv9bx1Dq8AvNlPnVbw',
    appId: '1:661569067297:ios:9da3a479287059338cc660',
    messagingSenderId: '661569067297',
    projectId: 'eaglone-auth',
    storageBucket: 'eaglone-auth.appspot.com',
    iosClientId: '661569067297-iromejaju6dcu28rop5e8e5of2n9kmlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eaglone',
  );
}
